# Generated by Django 5.2.5 on 2025-10-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='mpoly',
        ),
        migrations.AddField(
            model_name='worldborder',
            name='mpoly_json',
            field=models.TextField(default='{"type":"MultiPolygon","coordinates":[]'),
        ),
    ]
