# Generated by Django 5.2.5 on 2025-10-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='orders_by_region',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='movie',
            name='views_by_region',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
