# Generated by Django 5.0 on 2025-10-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_thumbs_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='thumbs',
            field=models.BooleanField(default=None),
        ),
    ]
