# Generated by Django 5.2.5 on 2025-10-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_orders_by_region_movie_views_by_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='orders_by_region',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='views_by_region',
        ),
    ]
