# Generated by Django 5.0 on 2025-10-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_review_thumbs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='thumbs',
            new_name='liked',
        ),
    ]
